languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Pailog"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02"
logo = "img/logo.png"
# logo = "img/blowfish_logo_transparent.png"
# description = "一个强大、轻量级的 Hugo 主题。"
# copyright = "Pailog"

[params.author]
name = "PaiBoo"
# image = "img/blowfish_logo.png"
image = "img/图层 0.png"
headline = "拾光成诗，与己偕长。" #包含作者头衔的 Markdown。它将展示在主页中作者姓名打分下方。
# bio = "拾光成诗，与己偕长。" #包含作者简介的 Markdown。它将展示在文章页脚。
## 与作者详细信息一起显示的链接。配置文件中包含示例链接，取消注释即可启用。链接展示的顺序由他们在数组中定义的顺序决定。如果你想自定义链接，可以在 assets/icons/ 中提供相应的SVG图片。
# links = [
#   { x-twitter = "https://twitter.com/burufugu" },
#   { github = "https://github.com/nunocoracao/blowfish" },
# ]
